package com.example.mobiledger.common.utils

object ConstantUtils {

    const val APP_NAME = "MobiLedger"
    const val USERS = "Users"
    const val EMAIL_ID = "emailId"
    const val USER_NAME = "userName"
    const val PHONE_NUMBER = "phoneNo"
    const val MONTH = "Months"
    const val TRANSACTION = "Transaction"
    const val NO_OF_EXPENSE_TRANSACTION = "noOfExpenseTransaction"
    const val NO_OF_INCOME_TRANSACTION = "noOfIncomeTransaction"
    const val NO_OF_TRANSACTION = "noOfTransaction"
    const val TOTAL_BALANCE = "totalBalance"
    const val TOTAL_INCOME = "totalIncome"
    const val TOTAL_EXPENSE = "totalExpense"
    const val UNAUTHORIZED_ERROR_MSG = "User is not authenticated"
    const val INCOME = "Income"
    const val EXPENSE = "Expense"
    const val CATEGORIES = "Categories"
    const val USER_CATEGORIES = "UserCategories"
    const val INCOME_CATEGORY_LIST = "incomeCategoryList"
    const val EXPENSE_CATEGORY_LIST = "expenseCategoryList"
    const val CATEGORY_TRANSACTION = "CategoryTransaction"
    const val MAX_BUDGET = "maxBudget"
    const val TOTAL_BUDGET = "totalBudget"
    const val BUDGET = "Budget"
    const val BUDGET_DETAILS = "budgetDetails"
    const val CATEGORY_BUDGET = "categoryBudget"
    const val REMINDER_CHANNEL = "Reminder channel"
    const val CHANNEL_ID_TRANSACTION = "ChannelIDTransaction"
    const val CATEGORY_AMOUNT = "categoryAmount"
    const val CATEGORY_EXPENSE = "categoryExpense"
    const val REMINDER_WORKER_TAG = "ReminderWorkerTag"
    const val CHANNEL_ID_REMINDER = "ChannelIDReminder"
    const val REMINDER_MESSAGE = "Don't miss thr transactions for the day!"
    const val DATA_REMINDER = "DATA_REMINDER"
    const val DAILY_REMINDER = "DAILY_REMINDER"
    const val OTHERS = "Others"
}